### ISSUE TITLE
previous/next buttons cutoff in projects

### ISSUE THREAD

**Issue by bgaid** [brenolf/brenolf.github.io#1]
Really cool site design! Found it through your Dash game posted to reddit.

I noticed this issue on your projects section. It may only affect certain use-cases. Basically the previous and next buttons are too low; half in the panel and half out.

![image](https://cloud.githubusercontent.com/assets/914337/6498733/612f403c-c2bd-11e4-8c92-c304d3e58737.png)

Changing the following fixes the issue on my screen.
.block-4 .centering.bottom {
position: absolute;
width: 80%;
~~bottom: 10%;~~
bottom: 15%;

I'm using Chrome on a 1440p monitor with default scaling.

**Comment by brenolf** [comment]
Hello! Thanks for letting me know and posting your solution. I will take a look at that as soon as possible.
